### ISSUE TITLE
Simulate Metrics with R4 real voting data

### ISSUE THREAD

**Issue by AngelaKTE** [GovXS/Evaluating-Voting-Design-Tradeoffs-for-Retro-Funding#37]
### Description

For our simulations, we take two approaches:

**a) compare voting rules:** we run experiments applying the Mallows model to generate artificial voting profiles and iterate over multiple rounds 

**b) assess risk in absolute numbers:** we run the experiments using a real set of voting data (e.g. R4 voting data) to see how the results in absolute numbers compare to a)

### Todo

@idrees535 please run the experiments on the following metrics with R4 voting data (1 round only)

* Robustness
* Bribery
* Control (removing voters)
* VEV (voter extractable value)

**Comment by idrees535** [comment]
Done
